#!/usr/bin/env python
import sys
import os
import platform
from shutil import copyfile
#Enables you to move a program file anywhere from source directory 
# You dont have to know OS commands just move/ change_dest/
#if help is requested interactive mode occurs
#have it execute from anywhere using the python command

list_files = []
profile_ = sys.argv[0];
dest = str(os.path.dirname(os.path.abspath(__file__)))
curdir = str(os.path.dirname(os.path.abspath(__file__)))
##def format_file_out(list_files):

#check for the source file argument vaule to be non-empty
#DONT allow someone to overwrite this file
#DONT allow to overwrite a file with same name/directory
def check_args():
	try:
		sys.argv[1]
	except:
		print(":Check for source arguments!!")
		exit(1)

check_args()
	
##Was able to print out main.py for the list
##allow user to change 
##
##
##
for index, args in enumerate(sys.argv):
	l=str(args)
	list_files.append(l)
	print(':a:')
	sys.stdout.write(l)

	##print("ARG:",args)
	##print("Index:",index)
	##print("Removed:",str(sys.argv[0]).replace("./",""))
	if(index>0):
		#remove ./ from first argumentto compare
		if(args!= str(sys.argv[0]).replace("./","")):
			##append files to list		
			##append to stdout
			##not sure what to do
			##
			## will work on 5-1-2017, 12:01pm
				
		else:
			sys.stdout.flush()
			print(" \nNot me, Update your arguments;p!! ")
			#needs to print out argument and index
			print("Check argument:",l,", at index:",
				index)
			exit(1)

sys.stdout.flush()
print(list_files,end='')
def dest_syntax():
	for fls in list_files:
		if(platform.system()=="Windows"):
			sender = curdir +"\\"
			src = curdir+fls
		
		else:
			cudir+="/"
			src = curdir+fls
	print('\n')
	print("Moving File: ",fls)
	src = curdir+fls
	print("Source:  ",src)
	print(dest)

	

#copyfile(filename1, "C:\Users\reeves\python\TODOL\")
